[workspace]

members = [
    "cli",
    "contracts/location",
    "contracts/pike",
    "contracts/product",
    "contracts/purchase_order",
    "contracts/schema",
    "contracts/track_and_trace",
    "daemon",
    "griddle",
    "sdk"
]
