# Copyright 2018-2020 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "grid-sdk"
version = "0.2.1"
authors = ["Cargill Incorporated"]
description = """\
    Hyperledger Grid is a platform for building supply chain solutions \
    that include distributed ledger components. It provides a growing \
    set of tools that accelerate development for supply chain smart contracts\
    and client interfaces.
"""
homepage = "https://grid.hyperledger.org"
edition = "2018"
license = "Apache-2.0"


[dependencies]
actix-web = { version = "3", optional = true }
base64 = { version = "0.10", optional = true }
byteorder = "1"
cfg-if = "0.1"
diesel = { version = "1.0", features = ["r2d2", "serde_json"], optional = true }
diesel_migrations = { version = "1.4", optional = true }
log = { version = "0.4", optional = true }
futures = { version = "0.3", optional = true }
futures-util = { version = "0.3", optional = true }
reqwest = { version = "0.10.1", features = ["json"], optional = true }
protobuf = "2.19"
sabre-sdk = { version = "0.5", optional = true }
sawtooth-sdk = { version = "0.4", features = ["transact-compat"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_derive = { version = "1.0" }
serde_json = { version = "1.0", optional = true }
url = { version = "2.1", optional = true }
uuid = { version = "0.6", features = ["v4"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
rust-crypto-wasm = "0.3"
sabre-sdk = "0.5"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cylinder = { version = "0.2.2", features = ["key-load"], optional = true}
rust-crypto = "0.2"
sawtooth-sdk = "0.4"

[build-dependencies]
protoc-rust = "2.14"
glob = "0.2"

[features]
default = []

stable = [
    # The stable feature extends default:
    "default",
    # The following features are stable:
    "batch-submitter",
    "location",
    "pike",
    "product",
    "schema",
]

experimental = [
    # The experimental feature extends stable:
    "stable",
    # The following features are experimental:
    "batch-store",
    "client",
    "postgres",
    "pike-rest-api",
    "purchase-order",
    "rest-api-resources",
    "rest-api-actix-web-3",
    "sawtooth-compat",
    "sqlite",
    "track-and-trace",
    "workflow"
]

client = []
location = ["pike", "schema"]
pike = []
pike-rest-api = ["pike", "serde_json", "rest-api-resources"]
purchase-order = []
product = ["pike", "schema"]
schema = ["pike"]
track-and-trace = ["base64"]
batch-store = []
batch-submitter = ["base64", "futures", "reqwest", "uuid", "url"]

postgres = ["diesel/postgres", "diesel_migrations", "log"]
rest-api-actix-web-3 = [
    "actix-web", "futures", "futures-util", "rest-api-resources", "sqlite", "postgres", "url"]
rest-api-resources = ["cylinder", "sabre-sdk", "log", "reqwest", "serde_json", "url"]
sawtooth-compat = [
    "sabre-sdk",
    "sawtooth-sdk"
]
sqlite = ["diesel/sqlite", "diesel_migrations"]
workflow = []
