# Copyright 2022 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------
version: '3.7'

services:

# --== contracts ==--

  tnt:
    image: tnt-contract-builder:${ISOLATION_ID}
    container_name: tnt-contract-builder
    build:
      context: ../../
      dockerfile: contracts/track_and_trace/Dockerfile
      args:
        - REPO_VERSION=${REPO_VERSION}
    volumes:
      - ../../build/scar:/build/scar
    entrypoint: |
      bash -c "
        cp /tmp/*.scar /build/scar
      "

  schema:
    image: schema-contract-builder:${ISOLATION_ID}
    container_name: schema-contract-builder
    build:
      context: ../../
      dockerfile: contracts/schema/Dockerfile
      args:
        - REPO_VERSION=${REPO_VERSION}
    volumes:
      - ../../build/scar:/build/scar
    entrypoint: |
      bash -c "
        cp /tmp/*.scar /build/scar
      "

  pike:
    image: pike-contract-builder:${ISOLATION_ID}
    container_name: pike-contract-builder
    build:
      context: ../../
      dockerfile: contracts/pike/Dockerfile
      args:
        - REPO_VERSION=${REPO_VERSION}
    volumes:
      - ../../build/scar:/build/scar
    entrypoint: |
      bash -c "
        cp /tmp/*.scar /build/scar
      "

  product:
    image: product-contract-builder:${ISOLATION_ID}
    container_name: product-contract-builder
    build:
      context: ../../
      dockerfile: contracts/product/Dockerfile
      args:
        - REPO_VERSION=${REPO_VERSION}
    volumes:
      - ../../build/scar:/build/scar
    entrypoint: |
      bash -c "
        cp /tmp/*.scar /build/scar
      "

  location:
    image: location-contract-builder:${ISOLATION_ID}
    container_name: location-contract-builder
    build:
      context: ../../
      dockerfile: contracts/location/Dockerfile
      args:
        - REPO_VERSION=${REPO_VERSION}
    volumes:
      - ../../build/scar:/build/scar
    entrypoint: |
      bash -c "
        cp /tmp/*.scar /build/scar
      "

  po:
    image: purchase-order-contract-builder:${ISOLATION_ID}
    container_name: purchase-order-contract-builder
    build:
      context: ../../
      dockerfile: contracts/purchase_order/Dockerfile
      args:
        - REPO_VERSION=${REPO_VERSION}
    volumes:
      - ../../build/scar:/build/scar
    entrypoint: |
      bash -c "
        cp /tmp/*.scar /build/scar
      "
